# Generated by Django 3.1.7 on 2021-03-25 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_type', models.CharField(choices=[('Song', 'Song'), ('Podcast', 'Podcast'), ('Audiobook', 'Audiobook')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('myaudio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myaudioapp.myaudio')),
                ('title_of_the_audiobook', models.CharField(max_length=100)),
                ('author_of_the_title', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('myaudioapp.myaudio',),
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('myaudio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myaudioapp.myaudio')),
                ('name_of_the_podcast', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(max_length=100)),
                ('participants', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            bases=('myaudioapp.myaudio',),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('myaudio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myaudioapp.myaudio')),
                ('name_of_the_song', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('myaudioapp.myaudio',),
        ),
    ]
